---
title: "Test process"
author: "Jim Greene"
date: "July 17, 2018"
output: html_document
---

### with parallel

idea:
  start r
  load package
  create cluster
  set up cluster environment
  process
  shut down cluster


```{r setup, include=FALSE}
library(parallel)
```

```{r}
# Calculate the number of cores
no_cores <- detectCores() - 1
 
# Initiate cluster
cl <- makeCluster(no_cores)
library(tidyverse)
clusterEvalQ(cl, library(tidyverse))
```


```{r}
#devtools::install_github("hathawayj/buildings")
library(buildings) # remember that the 'permits' data object is created when the library is loaded.
a <- 4
ff <- function(x){
  for (i in 1:1000){
    i
  }
  
  ggplot() + geom_point(x = permits[x, "value"])
  }

clusterExport(cl, varlist = c("a", "ff", "permits"))
```

```{r}
list_object <- as.list(1:7500)

system.time(temp1 <- lapply(list_object, ff))
system.time(temp2 <- parLapply(cl, list_object, ff))
```

```{r}
stopCluster(cl)

```


### with furrr:

we create a plan 
then process. (it creates the cluster everytime. (can be a bad thing , but is useful))
```{r}
pacman::p_load(furrr, purrr, tidyverse, tictoc)
```

```{r}
no_cores <- availableCores() - 1
plan(multiprocess, workers = no_cores) # ?plan
```

https://byuistats.github.io/M335/parallel_furrr.html

```{r}
# load libraries
#devtools::install_github("hathawayj/buildings")
library(buildings) # remember that the 'permits' data object is created when the library is loaded.
a <- 4
ff <- function(x){
  for (i in 1:1000){
    i
  }
  
  ggplot() + geom_point(x = permits[x, "value"])
}
list_object <- as.list(1:7500)
```

```{r}
tic()
temp1 <- map(list_object, ff)
toc()
```

```{r}
tic()
temp1 <- future_map(list_object, ff)
toc()
```

```{r}
second_sequence <- rep(5, 8)

tic()
nothingness <- map(second_sequence, ~Sys.sleep(.x))
toc()

plan(sequential)
tic()
nothingness <- future_map(second_sequence, ~Sys.sleep(.x))
toc()

plan(multiprocess)
tic()
nothingness <- future_map(second_sequence, ~Sys.sleep(.x))
toc()
```

