---
title: "Task 15"
author: "Jim Greene"
date: "June 12, 2018"
output: 
  html_document:
    keep_md: true
    theme: cerulean
    code_folding: hide
    
---

```{r setup, include=FALSE}
library(tidyverse)
library(riem)
library(lubridate)
```

```{r, eval = F}
rxe <- riem_measures(station = "RXE", date_start = "2015-06-01", date_end = "2017-07-01")
write_csv(rxe, "data/rxe.csv")
write_csv(rxe[2:5], "data/rxe_short.csv")
```

```{r}
#rxe <- read_csv("data/rxe_short.csv")
setwd("../")
rxe <- read_csv("../data/rxe_short.csv")
```

```{r}
rxe <- rxe %>% 
  ungroup() %>% 
  mutate(week_day = wday(valid), hour = hour(valid), week_day_name = wday(valid, label = T), year = year(valid), month = month(valid)) %>% 
  group_by(week_day_name, hour) %>% 
  mutate(max = max(tmpf, na.rm = T), avg = mean(tmpf, na.rm = T), low = min(tmpf, na.rm = T))
```

```{r, eval = F}
rxe %>%
  filter(month == 6) %>% 
  ggplot(aes(week_day_name, max, color = hour), size = 2) +
  geom_point()
```

```{r}
rxe %>% 
  filter(month == 6) %>% 
  ggplot(aes(x = hour, y = week_day_name, fill = max)) +
  geom_raster() +
  scale_x_continuous(breaks = seq(0, 23, by = 1)) +
  facet_wrap( ~ year, ncol = 1, scales = "free") +
  labs(x = "Hour", y = "", fill = "Max Temp (F)") +
  scale_fill_gradient2(low = "#778844", mid = "#88DD00", high = "#FF0000", midpoint = 70)
```

The hottest day was a Monday.

```{r}
rxe %>% 
  filter(hour == 2 & month == 6) %>% 
  ggplot(aes(week_day_name, 1, fill = low)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "x") + 
  labs(x = "Day", fill = "Min Tempurature", title = "Lowest tempuratures for June, 2015-2017") +
  scale_fill_gradient("Min Tempurature", low = "#0055FF", high = "#662200")
```

I was trying to experiment with polor coordinates here.

```{r}
rxe %>% 
  filter(hour == 2 & month == 6) %>% 
  ggplot(aes(week_day_name, low, color = low)) +
  geom_point() +
  geom_line(group = "low")
#+  geom_text(label = stat, stat = "identity")
```

The record Friday is slightly lower.




```{r, eval = F}
rxe %>% 
  filter(hour == 2) %>% 
  mutate(seq_day = 1:nrow(filter(rxe, hour == 2))) %>% 
  ggplot(aes(week_day_name, seq_day)) +
  #facet_wrap(~ year, nrow = 1) +
  geom_contour(aes(z = tmpf))
```

```{r, eval = F}
rxe %>% 
  ggplot(aes(hour, week_day_name, color = max)) +
  geom_bin2d(stat = color)
  #coord_polar(theta = "x")
```

