---
title: "Task 20"
author: "Jim Greene"
date: "June 26, 2018"
output: 
  html_document: 
  keep_md: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(st)
library(maps)
library(sf)
library(downloader)
library(USAboundaries)
```

```{r}
get_sf_data <- function(data_url) {
  df <- tempfile()
  uf <- tempfile()
  download(data_url, df, mode = "wb")
  unzip(df, exdir = uf)

  shp_files <- list.files(uf, "*.shp", recursive = T, full.names = T)

  shape_data <- read_sf(shp_files)

  remove(df)
  remove(uf)
  
  return(shape_data)
}

shape_states <- get_sf_data("https://byuistats.github.io/M335/data/shp.zip")
shape_well <- get_sf_data("https://research.idwr.idaho.gov/gis/Spatial/Wells/WellConstruction/wells.zip")
shape_dam <- get_sf_data("https://research.idwr.idaho.gov/gis/Spatial/DamSafety/dam.zip")
shape_water <- get_sf_data("https://research.idwr.idaho.gov/gis/Spatial/Hydrography/streams_lakes/c_250k/hyd250.zip")
```

```{r}
center_idaho <- "+proj=moll +lat_0=45 +lon_0=-114 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
idaho_tr <- shape_states %>% st_transform(crs = center_idaho)
```


```{r}
ggplot() +
  geom_sf(data = filter(idaho_tr, StateName %in% "Idaho"), fill = "#deedec") +
  geom_sf(data = filter(shape_water, FEAT_NAME == "Snake River" | FEAT_NAME == "Henrys Fork"), color = "#20b4ea", size = 1.25) +
  geom_sf(data = filter(shape_dam, SurfaceAre >= 50), aes(size = SurfaceAre, color = "#d2e21d")) +
  geom_sf(data = filter(shape_well, Production >= 5000), aes(size = Production, color = "#199e04")) +
  scale_colour_manual(name = "", values = c('#d2e21d' = '#d2e21d','#199e04' = '#199e04'), labels = c('Dams', 'Wells')) +
  scale_fill_manual(values = c('#d2e21d' = '#d2e21d','#199e04' = '#199e04'), labels = c('Dams', 'Wells')) +
  guides(color = guide_legend(override.aes = list()), size = F) + # guide_legend(override.aes = list(color = "gray50"))) +
  theme_minimal()# +
  # theme(legend.position = "none")
```

