---
title: "TASK 12"
author: "Jim Greene"
date: "May 31, 2018"
output: 
  html_document:
    theme: default
    keep_md: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
```


```{r, eval = F, include = F}
read_lines("https://byuistats.github.io/M335/data/randomletters.txt") %>% 
  str_extract_all('.1700')# %>% 
  # str_c(sep = "split") %>% 
  # str_extract_all('split')
```

```{r}
text <- read_lines("https://byuistats.github.io/M335/data/randomletters.txt")
strsplit(text, split = "")[[1]][c(1, seq(0, 58000, by = 1700))]
```


```{r}
read_lines("https://byuistats.github.io/M335/data/randomletters_wnumbers.txt") %>%
  str_extract_all('[0123456789]+') %>% 
  unlist() %>% 
  plyr::mapvalues(., from = 1:26, to = letters)
```

```{r}
vowel_chains <- read_lines("https://byuistats.github.io/M335/data/randomletters.txt") %>% 
  str_extract_all('[a-zA-Z]{1,}') %>% 
  paste(collapse = "") %>% 
  str_extract_all('[aeiou]{1,}') %>% 
  unlist()

lengths <- c(rep(0,length(vowel_chains)))
i <-  0
for (string in vowel_chains) {
  i <- i + 1
  lengths[i] <- nchar(string)
}
tibble(vowel_chains, lengths) %>% 
  arrange(desc(lengths))
```

